language: C
compiler: clang
script: cmake . && make 
before_install: 
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=I6M9GXLv0oUPr7JEUIVhOQMu8eJdl49GB
  - sudo apt-get install -qq libpcap-dev
  #- ./install-cmocka.sh